/**
 * Flyo Nitro CMS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.127
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Config200ResponsePagesInner model module.
 * @module model/Config200ResponsePagesInner
 * @version 1.0.0-beta.127
 */
class Config200ResponsePagesInner {
    /**
     * Constructs a new <code>Config200ResponsePagesInner</code>.
     * @alias module:model/Config200ResponsePagesInner
     * @param {(module:model/String)} instance The actual instance to initialize Config200ResponsePagesInner.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `Config200ResponsePagesInner` with oneOf schemas String. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `Config200ResponsePagesInner` with oneOf schemas String. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>Config200ResponsePagesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Config200ResponsePagesInner} obj Optional instance to populate.
     * @return {module:model/Config200ResponsePagesInner} The populated <code>Config200ResponsePagesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        return new Config200ResponsePagesInner(data);
    }

    /**
     * Gets the actual instance, which can be <code>String</code>.
     * @return {(module:model/String)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>String</code>.
     * @param {(module:model/String)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = Config200ResponsePagesInner.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of Config200ResponsePagesInner from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/Config200ResponsePagesInner} An instance of Config200ResponsePagesInner.
     */
    static fromJSON = function(json_string){
        return Config200ResponsePagesInner.constructFromObject(JSON.parse(json_string));
    }
}


Config200ResponsePagesInner.OneOf = ["String"];

export default Config200ResponsePagesInner;

