/**
 * Flyo Nitro CMS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.127
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Config200ResponseNitro model module.
 * @module model/Config200ResponseNitro
 * @version 1.0.0-beta.127
 */
class Config200ResponseNitro {
    /**
     * Constructs a new <code>Config200ResponseNitro</code>.
     * @alias module:model/Config200ResponseNitro
     */
    constructor() { 
        
        Config200ResponseNitro.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Config200ResponseNitro</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Config200ResponseNitro} obj Optional instance to populate.
     * @return {module:model/Config200ResponseNitro} The populated <code>Config200ResponseNitro</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Config200ResponseNitro();

            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Number');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Config200ResponseNitro</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Config200ResponseNitro</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['domain'] && !(typeof data['domain'] === 'string' || data['domain'] instanceof String)) {
            throw new Error("Expected the field `domain` to be a primitive type in the JSON string but got " + data['domain']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }
        // ensure the json data is a string
        if (data['language'] && !(typeof data['language'] === 'string' || data['language'] instanceof String)) {
            throw new Error("Expected the field `language` to be a primitive type in the JSON string but got " + data['language']);
        }

        return true;
    }


}



/**
 * @member {String} domain
 */
Config200ResponseNitro.prototype['domain'] = undefined;

/**
 * @member {String} slug
 */
Config200ResponseNitro.prototype['slug'] = undefined;

/**
 * Whenever flyo generates new data, this version will be increased. This can be used for cache informnations.
 * @member {Number} version
 */
Config200ResponseNitro.prototype['version'] = undefined;

/**
 * @member {Number} updated_at
 */
Config200ResponseNitro.prototype['updated_at'] = undefined;

/**
 * @member {String} language
 */
Config200ResponseNitro.prototype['language'] = undefined;






export default Config200ResponseNitro;

