/**
 * Flyo Nitro Cms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.125
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PagesInner from './PagesInner';

/**
 * The Config200ResponseNav model module.
 * @module model/Config200ResponseNav
 * @version 1.0.0-beta.125
 */
class Config200ResponseNav {
    /**
     * Constructs a new <code>Config200ResponseNav</code>.
     * @alias module:model/Config200ResponseNav
     */
    constructor() { 
        
        Config200ResponseNav.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Config200ResponseNav</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Config200ResponseNav} obj Optional instance to populate.
     * @return {module:model/Config200ResponseNav} The populated <code>Config200ResponseNav</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Config200ResponseNav();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [PagesInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Config200ResponseNav</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Config200ResponseNav</code>.
     */
    static validateJSON(data) {
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                PagesInner.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/PagesInner>} items
 */
Config200ResponseNav.prototype['items'] = undefined;






export default Config200ResponseNav;

