/**
 * Flyo Nitro Cms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.126
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Entity200ResponseEntityEntityMetric from './Entity200ResponseEntityEntityMetric';

/**
 * The Entity200ResponseEntity model module.
 * @module model/Entity200ResponseEntity
 * @version 1.0.0-beta.126
 */
class Entity200ResponseEntity {
    /**
     * Constructs a new <code>Entity200ResponseEntity</code>.
     * @alias module:model/Entity200ResponseEntity
     */
    constructor() { 
        
        Entity200ResponseEntity.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Entity200ResponseEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Entity200ResponseEntity} obj Optional instance to populate.
     * @return {module:model/Entity200ResponseEntity} The populated <code>Entity200ResponseEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Entity200ResponseEntity();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('_version')) {
                obj['_version'] = ApiClient.convertToType(data['_version'], 'Number');
            }
            if (data.hasOwnProperty('entity_metric')) {
                obj['entity_metric'] = Entity200ResponseEntityEntityMetric.constructFromObject(data['entity_metric']);
            }
            if (data.hasOwnProperty('entity_unique_id')) {
                obj['entity_unique_id'] = ApiClient.convertToType(data['entity_unique_id'], 'String');
            }
            if (data.hasOwnProperty('entity_id')) {
                obj['entity_id'] = ApiClient.convertToType(data['entity_id'], 'String');
            }
            if (data.hasOwnProperty('entity_image')) {
                obj['entity_image'] = ApiClient.convertToType(data['entity_image'], 'String');
            }
            if (data.hasOwnProperty('entity_slug')) {
                obj['entity_slug'] = ApiClient.convertToType(data['entity_slug'], 'String');
            }
            if (data.hasOwnProperty('entity_teaser')) {
                obj['entity_teaser'] = ApiClient.convertToType(data['entity_teaser'], 'String');
            }
            if (data.hasOwnProperty('entity_time_end')) {
                obj['entity_time_end'] = ApiClient.convertToType(data['entity_time_end'], 'String');
            }
            if (data.hasOwnProperty('entity_time_start')) {
                obj['entity_time_start'] = ApiClient.convertToType(data['entity_time_start'], 'String');
            }
            if (data.hasOwnProperty('entity_title')) {
                obj['entity_title'] = ApiClient.convertToType(data['entity_title'], 'String');
            }
            if (data.hasOwnProperty('entity_type')) {
                obj['entity_type'] = ApiClient.convertToType(data['entity_type'], 'String');
            }
            if (data.hasOwnProperty('entity_type_id')) {
                obj['entity_type_id'] = ApiClient.convertToType(data['entity_type_id'], 'Number');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Entity200ResponseEntity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Entity200ResponseEntity</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['_id'] && !(typeof data['_id'] === 'string' || data['_id'] instanceof String)) {
            throw new Error("Expected the field `_id` to be a primitive type in the JSON string but got " + data['_id']);
        }
        // validate the optional field `entity_metric`
        if (data['entity_metric']) { // data not null
          Entity200ResponseEntityEntityMetric.validateJSON(data['entity_metric']);
        }
        // ensure the json data is a string
        if (data['entity_unique_id'] && !(typeof data['entity_unique_id'] === 'string' || data['entity_unique_id'] instanceof String)) {
            throw new Error("Expected the field `entity_unique_id` to be a primitive type in the JSON string but got " + data['entity_unique_id']);
        }
        // ensure the json data is a string
        if (data['entity_id'] && !(typeof data['entity_id'] === 'string' || data['entity_id'] instanceof String)) {
            throw new Error("Expected the field `entity_id` to be a primitive type in the JSON string but got " + data['entity_id']);
        }
        // ensure the json data is a string
        if (data['entity_image'] && !(typeof data['entity_image'] === 'string' || data['entity_image'] instanceof String)) {
            throw new Error("Expected the field `entity_image` to be a primitive type in the JSON string but got " + data['entity_image']);
        }
        // ensure the json data is a string
        if (data['entity_slug'] && !(typeof data['entity_slug'] === 'string' || data['entity_slug'] instanceof String)) {
            throw new Error("Expected the field `entity_slug` to be a primitive type in the JSON string but got " + data['entity_slug']);
        }
        // ensure the json data is a string
        if (data['entity_teaser'] && !(typeof data['entity_teaser'] === 'string' || data['entity_teaser'] instanceof String)) {
            throw new Error("Expected the field `entity_teaser` to be a primitive type in the JSON string but got " + data['entity_teaser']);
        }
        // ensure the json data is a string
        if (data['entity_time_end'] && !(typeof data['entity_time_end'] === 'string' || data['entity_time_end'] instanceof String)) {
            throw new Error("Expected the field `entity_time_end` to be a primitive type in the JSON string but got " + data['entity_time_end']);
        }
        // ensure the json data is a string
        if (data['entity_time_start'] && !(typeof data['entity_time_start'] === 'string' || data['entity_time_start'] instanceof String)) {
            throw new Error("Expected the field `entity_time_start` to be a primitive type in the JSON string but got " + data['entity_time_start']);
        }
        // ensure the json data is a string
        if (data['entity_title'] && !(typeof data['entity_title'] === 'string' || data['entity_title'] instanceof String)) {
            throw new Error("Expected the field `entity_title` to be a primitive type in the JSON string but got " + data['entity_title']);
        }
        // ensure the json data is a string
        if (data['entity_type'] && !(typeof data['entity_type'] === 'string' || data['entity_type'] instanceof String)) {
            throw new Error("Expected the field `entity_type` to be a primitive type in the JSON string but got " + data['entity_type']);
        }
        // ensure the json data is a string
        if (data['updated_at'] && !(typeof data['updated_at'] === 'string' || data['updated_at'] instanceof String)) {
            throw new Error("Expected the field `updated_at` to be a primitive type in the JSON string but got " + data['updated_at']);
        }

        return true;
    }


}



/**
 * An identifier from the database index
 * @member {String} _id
 */
Entity200ResponseEntity.prototype['_id'] = undefined;

/**
 * A sequential index as version of the item
 * @member {Number} _version
 */
Entity200ResponseEntity.prototype['_version'] = undefined;

/**
 * @member {module:model/Entity200ResponseEntityEntityMetric} entity_metric
 */
Entity200ResponseEntity.prototype['entity_metric'] = undefined;

/**
 * @member {String} entity_unique_id
 */
Entity200ResponseEntity.prototype['entity_unique_id'] = undefined;

/**
 * @member {String} entity_id
 */
Entity200ResponseEntity.prototype['entity_id'] = undefined;

/**
 * @member {String} entity_image
 */
Entity200ResponseEntity.prototype['entity_image'] = undefined;

/**
 * @member {String} entity_slug
 */
Entity200ResponseEntity.prototype['entity_slug'] = undefined;

/**
 * @member {String} entity_teaser
 */
Entity200ResponseEntity.prototype['entity_teaser'] = undefined;

/**
 * @member {String} entity_time_end
 */
Entity200ResponseEntity.prototype['entity_time_end'] = undefined;

/**
 * @member {String} entity_time_start
 */
Entity200ResponseEntity.prototype['entity_time_start'] = undefined;

/**
 * @member {String} entity_title
 */
Entity200ResponseEntity.prototype['entity_title'] = undefined;

/**
 * @member {String} entity_type
 */
Entity200ResponseEntity.prototype['entity_type'] = undefined;

/**
 * @member {Number} entity_type_id
 */
Entity200ResponseEntity.prototype['entity_type_id'] = undefined;

/**
 * @member {String} updated_at
 */
Entity200ResponseEntity.prototype['updated_at'] = undefined;






export default Entity200ResponseEntity;

