/**
 * Flyo Nitro CMS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.127
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PagePropertyValue from './PagePropertyValue';

/**
 * The PageProperty model module.
 * @module model/PageProperty
 * @version 1.0.0-beta.127
 */
class PageProperty {
    /**
     * Constructs a new <code>PageProperty</code>.
     * @alias module:model/PageProperty
     */
    constructor() { 
        
        PageProperty.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PageProperty</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PageProperty} obj Optional instance to populate.
     * @return {module:model/PageProperty} The populated <code>PageProperty</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageProperty();

            if (data.hasOwnProperty('value')) {
                obj['value'] = PagePropertyValue.constructFromObject(data['value']);
            }
            if (data.hasOwnProperty('navigation')) {
                obj['navigation'] = ApiClient.convertToType(data['navigation'], 'Boolean');
            }
            if (data.hasOwnProperty('propagate')) {
                obj['propagate'] = ApiClient.convertToType(data['propagate'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PageProperty</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PageProperty</code>.
     */
    static validateJSON(data) {
        // validate the optional field `value`
        if (data['value']) { // data not null
          PagePropertyValue.validateJSON(data['value']);
        }

        return true;
    }


}



/**
 * @member {module:model/PagePropertyValue} value
 */
PageProperty.prototype['value'] = undefined;

/**
 * @member {Boolean} navigation
 */
PageProperty.prototype['navigation'] = undefined;

/**
 * @member {Boolean} propagate
 */
PageProperty.prototype['propagate'] = undefined;






export default PageProperty;

