/**
 * Flyo Nitro CMS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PagePropertyValue model module.
 * @module model/PagePropertyValue
 * @version 1.0.0-beta.139
 */
class PagePropertyValue {
    /**
     * Constructs a new <code>PagePropertyValue</code>.
     * @alias module:model/PagePropertyValue
     * @param {(module:model/Boolean|module:model/Number|module:model/Object|module:model/String|module:model/[Object])} instance The actual instance to initialize PagePropertyValue.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        try {
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Object
            errorMessages.push("Failed to construct Object: " + err)
        }

        try {
            // validate integer
            if (!(typeof instance === 'number' && instance % 1 === 0)) {
                throw new Error("Invalid value. Must be integer. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Number
            errorMessages.push("Failed to construct Number: " + err)
        }

        try {
            // validate array data type
            if (!Array.isArray(instance)) {
                throw new Error("Invalid data type. Expecting array. Input: " + instance);
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into [Object]
            errorMessages.push("Failed to construct [Object]: " + err)
        }

        try {
            // validate boolean
            if (!(typeof instance === 'boolean')) {
                throw new Error("Invalid value. Must be boolean. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Boolean
            errorMessages.push("Failed to construct Boolean: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `PagePropertyValue` with oneOf schemas Boolean, Number, Object, String, [Object]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `PagePropertyValue` with oneOf schemas Boolean, Number, Object, String, [Object]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>PagePropertyValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PagePropertyValue} obj Optional instance to populate.
     * @return {module:model/PagePropertyValue} The populated <code>PagePropertyValue</code> instance.
     */
    static constructFromObject(data, obj) {
        return new PagePropertyValue(data);
    }

    /**
     * Gets the actual instance, which can be <code>Boolean</code>, <code>Number</code>, <code>Object</code>, <code>String</code>, <code>[Object]</code>.
     * @return {(module:model/Boolean|module:model/Number|module:model/Object|module:model/String|module:model/[Object])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>Boolean</code>, <code>Number</code>, <code>Object</code>, <code>String</code>, <code>[Object]</code>.
     * @param {(module:model/Boolean|module:model/Number|module:model/Object|module:model/String|module:model/[Object])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = PagePropertyValue.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of PagePropertyValue from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/PagePropertyValue} An instance of PagePropertyValue.
     */
    static fromJSON = function(json_string){
        return PagePropertyValue.constructFromObject(JSON.parse(json_string));
    }
}


PagePropertyValue.OneOf = ["Boolean", "Number", "Object", "String", "[Object]"];

export default PagePropertyValue;

