/**
 * Flyo Nitro Cms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.126
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Block from './Block';

/**
 * The Page model module.
 * @module model/Page
 * @version 1.0.0-beta.126
 */
class Page {
    /**
     * Constructs a new <code>Page</code>.
     * @alias module:model/Page
     */
    constructor() { 
        
        Page.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Page</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Page} obj Optional instance to populate.
     * @return {module:model/Page} The populated <code>Page</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Page();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('nitro_id')) {
                obj['nitro_id'] = ApiClient.convertToType(data['nitro_id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('page_page_id')) {
                obj['page_page_id'] = ApiClient.convertToType(data['page_page_id'], 'Number');
            }
            if (data.hasOwnProperty('depth')) {
                obj['depth'] = ApiClient.convertToType(data['depth'], 'Number');
            }
            if (data.hasOwnProperty('sort_index')) {
                obj['sort_index'] = ApiClient.convertToType(data['sort_index'], 'Number');
            }
            if (data.hasOwnProperty('is_online')) {
                obj['is_online'] = ApiClient.convertToType(data['is_online'], 'Number');
            }
            if (data.hasOwnProperty('is_home')) {
                obj['is_home'] = ApiClient.convertToType(data['is_home'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Number');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Number');
            }
            if (data.hasOwnProperty('is_visible')) {
                obj['is_visible'] = ApiClient.convertToType(data['is_visible'], 'Number');
            }
            if (data.hasOwnProperty('meta_json')) {
                obj['meta_json'] = ApiClient.convertToType(data['meta_json'], 'Number');
            }
            if (data.hasOwnProperty('json')) {
                obj['json'] = ApiClient.convertToType(data['json'], [Block]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Page</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Page</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }
        if (data['json']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['json'])) {
                throw new Error("Expected the field `json` to be an array in the JSON data but got " + data['json']);
            }
            // validate the optional field `json` (array)
            for (const item of data['json']) {
                Block.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
Page.prototype['id'] = undefined;

/**
 * @member {Number} nitro_id
 */
Page.prototype['nitro_id'] = undefined;

/**
 * @member {String} title
 */
Page.prototype['title'] = undefined;

/**
 * @member {String} slug
 */
Page.prototype['slug'] = undefined;

/**
 * @member {Number} page_page_id
 */
Page.prototype['page_page_id'] = undefined;

/**
 * @member {Number} depth
 */
Page.prototype['depth'] = undefined;

/**
 * @member {Number} sort_index
 */
Page.prototype['sort_index'] = undefined;

/**
 * @member {Number} is_online
 */
Page.prototype['is_online'] = undefined;

/**
 * @member {Number} is_home
 */
Page.prototype['is_home'] = undefined;

/**
 * @member {Number} created_at
 */
Page.prototype['created_at'] = undefined;

/**
 * @member {Number} updated_at
 */
Page.prototype['updated_at'] = undefined;

/**
 * @member {Number} is_visible
 */
Page.prototype['is_visible'] = undefined;

/**
 * @member {Number} meta_json
 */
Page.prototype['meta_json'] = undefined;

/**
 * @member {Array.<module:model/Block>} json
 */
Page.prototype['json'] = undefined;






export default Page;

