/**
 * Flyo Nitro CMS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SitemapResponseInner model module.
 * @module model/SitemapResponseInner
 * @version 1.0.0-beta.139
 */
class SitemapResponseInner {
    /**
     * Constructs a new <code>SitemapResponseInner</code>.
     * @alias module:model/SitemapResponseInner
     */
    constructor() { 
        
        SitemapResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SitemapResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SitemapResponseInner} obj Optional instance to populate.
     * @return {module:model/SitemapResponseInner} The populated <code>SitemapResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SitemapResponseInner();

            if (data.hasOwnProperty('entity_unique_id')) {
                obj['entity_unique_id'] = ApiClient.convertToType(data['entity_unique_id'], 'String');
            }
            if (data.hasOwnProperty('entity_title')) {
                obj['entity_title'] = ApiClient.convertToType(data['entity_title'], 'String');
            }
            if (data.hasOwnProperty('entity_teaser')) {
                obj['entity_teaser'] = ApiClient.convertToType(data['entity_teaser'], 'String');
            }
            if (data.hasOwnProperty('entity_slug')) {
                obj['entity_slug'] = ApiClient.convertToType(data['entity_slug'], 'String');
            }
            if (data.hasOwnProperty('entity_type')) {
                obj['entity_type'] = ApiClient.convertToType(data['entity_type'], 'String');
            }
            if (data.hasOwnProperty('entity_type_id')) {
                obj['entity_type_id'] = ApiClient.convertToType(data['entity_type_id'], 'Number');
            }
            if (data.hasOwnProperty('entity_time_start')) {
                obj['entity_time_start'] = ApiClient.convertToType(data['entity_time_start'], 'String');
            }
            if (data.hasOwnProperty('entity_image')) {
                obj['entity_image'] = ApiClient.convertToType(data['entity_image'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SitemapResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SitemapResponseInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['entity_unique_id'] && !(typeof data['entity_unique_id'] === 'string' || data['entity_unique_id'] instanceof String)) {
            throw new Error("Expected the field `entity_unique_id` to be a primitive type in the JSON string but got " + data['entity_unique_id']);
        }
        // ensure the json data is a string
        if (data['entity_title'] && !(typeof data['entity_title'] === 'string' || data['entity_title'] instanceof String)) {
            throw new Error("Expected the field `entity_title` to be a primitive type in the JSON string but got " + data['entity_title']);
        }
        // ensure the json data is a string
        if (data['entity_teaser'] && !(typeof data['entity_teaser'] === 'string' || data['entity_teaser'] instanceof String)) {
            throw new Error("Expected the field `entity_teaser` to be a primitive type in the JSON string but got " + data['entity_teaser']);
        }
        // ensure the json data is a string
        if (data['entity_slug'] && !(typeof data['entity_slug'] === 'string' || data['entity_slug'] instanceof String)) {
            throw new Error("Expected the field `entity_slug` to be a primitive type in the JSON string but got " + data['entity_slug']);
        }
        // ensure the json data is a string
        if (data['entity_type'] && !(typeof data['entity_type'] === 'string' || data['entity_type'] instanceof String)) {
            throw new Error("Expected the field `entity_type` to be a primitive type in the JSON string but got " + data['entity_type']);
        }
        // ensure the json data is a string
        if (data['entity_time_start'] && !(typeof data['entity_time_start'] === 'string' || data['entity_time_start'] instanceof String)) {
            throw new Error("Expected the field `entity_time_start` to be a primitive type in the JSON string but got " + data['entity_time_start']);
        }
        // ensure the json data is a string
        if (data['entity_image'] && !(typeof data['entity_image'] === 'string' || data['entity_image'] instanceof String)) {
            throw new Error("Expected the field `entity_image` to be a primitive type in the JSON string but got " + data['entity_image']);
        }

        return true;
    }


}



/**
 * Unique ID
 * @member {String} entity_unique_id
 */
SitemapResponseInner.prototype['entity_unique_id'] = undefined;

/**
 * @member {String} entity_title
 */
SitemapResponseInner.prototype['entity_title'] = undefined;

/**
 * @member {String} entity_teaser
 */
SitemapResponseInner.prototype['entity_teaser'] = undefined;

/**
 * @member {String} entity_slug
 */
SitemapResponseInner.prototype['entity_slug'] = undefined;

/**
 * @member {String} entity_type
 */
SitemapResponseInner.prototype['entity_type'] = undefined;

/**
 * @member {Number} entity_type_id
 */
SitemapResponseInner.prototype['entity_type_id'] = undefined;

/**
 * @member {String} entity_time_start
 */
SitemapResponseInner.prototype['entity_time_start'] = undefined;

/**
 * @member {String} entity_image
 */
SitemapResponseInner.prototype['entity_image'] = undefined;






export default SitemapResponseInner;

