/**
 * Flyo Nitro
 * This document provides a comprehensive overview of all the endpoints available for Flyo Nitro, a powerful platform designed to facilitate the development of websites. Flyo Nitro is built upon three strategic pillars that play a central role in website development:  + Config: The config component is responsible for loading all the necessary elements required for seamless navigation within the website layout. This includes crucial elements like the navigation menu or global content, such as the \"Locations\" section of an entity, which can be utilized in the footer across all pages. + Pages: Pages are evaluated based on their unique slug (path) and encompass all the content needed to populate a specific page. This includes various content elements, known as blocks, as well as meta information like \"og-descriptions.\" Additionally, pages can dynamically incorporate content from entities by employing mapping techniques. + Entity: Entities can be retrieved by utilizing a unique identifier, which can be configured within Flyo Nitro. Each entity provides comprehensive details in the form of fields, offering specific content tailored to a particular context.  Furthermore, it is important to distinguish between the **development** and **production** environments in Flyo Nitro. In the development environment, any changes made to data within the Flyo User Interface are immediately accessible, even without saving. This feature enables users to have a live preview of the changes during data entry. On the other hand, the production environment exclusively utilizes saved data, ensuring that only finalized content is displayed.  For more detailed documentation in German, please visit: https://docs.flyo.cloud/doc/integrations-nitro-cms
 *
 * The version of the OpenAPI document: 2.28
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EntityinterfaceInner from '../model/EntityinterfaceInner';

/**
* Search service.
* @module api/SearchApi
* @version 2.28
*/
export default class SearchApi {

    /**
    * Constructs a new SearchApi. 
    * @alias module:api/SearchApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get Search by query
     * This endpoint offers a powerful full-text search through the websites sitemap, encompassing both pages and entities. It performs word-based matching against entity titles and teasers. Each result includes a `score` field representing the relevance of the match. By default, results are sorted by relevance (highest score first). Each result also includes an `href` attribute containing the resolved URL path for the entity. In multi-lingual setups, search results are automatically filtered to match the current language context specified via the `lang` parameter, ensuring only results relevant to the requested language are returned.
     * @param {String} query The query keyword that needs to be looked up. It is important to ensure that the query is properly URL encoded for accurate processing and retrieval.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} [sort] Optional sort field. If not provided, results are sorted by `score` (relevance) by default which is the recommended behavior for search. The `score` value reflects how well the result matches the query — higher scores indicate better matches. Use `-` as a prefix for descending order (for example `-title`). Ascending order uses the plain field name (for example `title`). A `+` prefix is not supported. The `time_start` field is derived from the shared entity time interface and is only meaningful for entities that implement it; entities without that interface return `time_start` as `0`, so use this sort carefully.
     * @param {Number} [page = 1)] The page number for paginated results. Defaults to 1 if not provided.
     * @param {String} [lang] Specifies the language context for the current request. If not provided, the default primary language will be used. This parameter has no effect if the Nitro setup is not configured for multiple languages.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/EntityinterfaceInner>} and HTTP response
     */
    searchWithHttpInfo(query, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'query' is set
      if (query === undefined || query === null) {
        throw new Error("Missing the required parameter 'query' when calling search");
      }

      let pathParams = {
      };
      let queryParams = {
        'query': query,
        'sort': opts['sort'],
        'page': opts['page'],
        'lang': opts['lang']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [EntityinterfaceInner];
      return this.apiClient.callApi(
        '/search', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Search by query
     * This endpoint offers a powerful full-text search through the websites sitemap, encompassing both pages and entities. It performs word-based matching against entity titles and teasers. Each result includes a `score` field representing the relevance of the match. By default, results are sorted by relevance (highest score first). Each result also includes an `href` attribute containing the resolved URL path for the entity. In multi-lingual setups, search results are automatically filtered to match the current language context specified via the `lang` parameter, ensuring only results relevant to the requested language are returned.
     * @param {String} query The query keyword that needs to be looked up. It is important to ensure that the query is properly URL encoded for accurate processing and retrieval.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.sort Optional sort field. If not provided, results are sorted by `score` (relevance) by default which is the recommended behavior for search. The `score` value reflects how well the result matches the query — higher scores indicate better matches. Use `-` as a prefix for descending order (for example `-title`). Ascending order uses the plain field name (for example `title`). A `+` prefix is not supported. The `time_start` field is derived from the shared entity time interface and is only meaningful for entities that implement it; entities without that interface return `time_start` as `0`, so use this sort carefully.
     * @param {Number} opts.page The page number for paginated results. Defaults to 1 if not provided. (default to 1)
     * @param {String} opts.lang Specifies the language context for the current request. If not provided, the default primary language will be used. This parameter has no effect if the Nitro setup is not configured for multiple languages.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/EntityinterfaceInner>}
     */
    search(query, opts) {
      return this.searchWithHttpInfo(query, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
