/**
 * Flyo Nitro CMS
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta.140
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import SitemapResponseInner from '../model/SitemapResponseInner';

/**
* Sitemap service.
* @module api/SitemapApi
* @version 1.0.0-beta.140
*/
export default class SitemapApi {

    /**
    * Constructs a new SitemapApi. 
    * @alias module:api/SitemapApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get Sitemap
     * Get all entities to build a sitemap. Pages are not included.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/SitemapResponseInner>} and HTTP response
     */
    sitemapWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [SitemapResponseInner];
      return this.apiClient.callApi(
        '/sitemap', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Sitemap
     * Get all entities to build a sitemap. Pages are not included.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/SitemapResponseInner>}
     */
    sitemap() {
      return this.sitemapWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
